# Generated by Django 3.1 on 2020-09-09 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_information', models.TextField(default='')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=orders.models.should_send_date)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=4.99, max_digits=4)),
                ('status', models.CharField(choices=[('P', 'Processed'), ('S', 'Sent'), ('D', 'Delivered'), ('R', 'Received'), ('F', 'Finished')], default='P', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product_quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='orders.order')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='products.product')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_products',
            field=models.ManyToManyField(related_name='products', through='orders.OrderProduct', to='products.Product'),
        ),
    ]
