# Generated by Django 3.0.8 on 2020-08-16 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import functools
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_days', models.IntegerField(default=1)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('day_of_sending', models.DateTimeField(default=functools.partial(orders.models.should_send_date, *(models.IntegerField(default=1),), **{}))),
                ('ordered_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_product', to='products.Product')),
            ],
        ),
    ]
