# Generated by Django 3.1 on 2020-08-22 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=orders.models.should_send_date)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_product', to='products.product')),
            ],
        ),
    ]
