# Generated by Django 3.1 on 2020-08-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Processed'), ('S', 'Sent'), ('D', 'Delivered'), ('R', 'Received')], default='F', max_length=20),
            preserve_default=False,
        ),
    ]
