# Generated by Django 3.1 on 2020-08-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=2002.99, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Processed'), ('S', 'Sent'), ('D', 'Delivered'), ('R', 'Received'), ('F', 'Finished')], max_length=20),
        ),
    ]
