# Generated by Django 3.1 on 2020-09-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200823_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_information',
            field=models.TextField(default=''),
        ),
    ]
