# Generated by Django 3.1 on 2020-09-09 15:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, unique=True)),
                ('category', models.CharField(choices=[('A', 'Automotive'), ('B', 'Baby'), ('C', 'Computers'), ('F', 'Free'), ('S', 'Software'), ('BF', "Boys' Fashion"), ('GF', "Girl' Fashion"), ('MF', "Men's Fashion"), ('WF', "Women's Fashion"), ('HG', 'House and Garden'), ('RE', 'Real Estate'), ('SBH', 'Sports, Books, Hobby'), ('MTE', 'Machines, tools, equipment')], max_length=30)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('description', models.TextField(default='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('country', django_countries.fields.CountryField(blank=True, default='BG', max_length=2)),
                ('city', models.CharField(default='', max_length=150)),
                ('in_store', models.IntegerField(default=1)),
                ('url_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='products.product')),
            ],
        ),
    ]
