# Generated by Django 3.1 on 2020-09-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
